"""Adiciona autoincrement ao id dos items

Revision ID: 894c73d2c3e3
Revises: a7f5b41523e0
Create Date: 2025-06-16 03:12:48.058354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894c73d2c3e3'
down_revision: Union[str, None] = 'a7f5b41523e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Primeiro, remove o default antigo da coluna
    op.execute('ALTER TABLE items ALTER COLUMN id DROP DEFAULT')
    # Agora, adiciona o IDENTITY
    op.execute('ALTER TABLE items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY')

def downgrade() -> None:
    # No downgrade, remove o identity
    op.execute('ALTER TABLE items ALTER COLUMN id DROP IDENTITY IF EXISTS')
    # Se quiser, pode restaurar o default antigo 