"""Create missions and user_missions

Revision ID: 90f848fcb13a
Revises: 894c73d2c3e3
Create Date: 2025-06-16 04:58:55.290067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f848fcb13a'
down_revision: Union[str, None] = '894c73d2c3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'progresso')
    op.add_column('user_missions', sa.Column('progresso', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_missions', 'missions', ['mission_id'], ['id'])
    op.drop_column('user_missions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_missions', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_missions', type_='foreignkey')
    op.drop_column('user_missions', 'progresso')
    op.add_column('missions', sa.Column('progresso', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
