"""Adicionando campos de recompensa em Task

Revision ID: ab64bde930d7
Revises: 
Create Date: 2025-06-14 19:51:50.008438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab64bde930d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recompensa_moedas', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('recompensa_xp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recompensa_xp')
    op.drop_column('tasks', 'recompensa_moedas')
    # ### end Alembic commands ###
