"""Add item_ids array to user_items

Revision ID: f09aee2b9f05
Revises: ab64bde930d7
Create Date: 2025-06-15 20:21:27.187367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09aee2b9f05'
down_revision: Union[str, None] = 'ab64bde930d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_items', sa.Column('item_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.create_unique_constraint(None, 'user_items', ['user_id'])
    op.drop_constraint(op.f('user_items_item_id_fkey'), 'user_items', type_='foreignkey')
    op.drop_column('user_items', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_items', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_items_item_id_fkey'), 'user_items', 'items', ['item_id'], ['id'])
    op.drop_constraint(None, 'user_items', type_='unique')
    op.drop_column('user_items', 'item_ids')
    # ### end Alembic commands ###
